### ISSUE TITLE
Which Python versions are supported?

### ISSUE THREAD

**Issue by mgd722** [what3words/w3w-python-wrapper#6]
The docs should state that this module can be used in both Python 2 and 3 (if this is the case).

**Comment by tsamaya** [comment]
Tested on version 2.7; travis-ci planned within a couple of days to test versions from 2.6 to 3.4

**Comment by toni88x** [comment]
Seems like the current version doesn't work on Py3 because it depends on poster-0.8.1. Getting the following error from pip when trying to install on Python 3.5.2:

Collecting poster
  Using cached poster-0.8.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/2n/90xsl63x57bg30n9x03gjnqw0000gn/T/pip-build-cvncr6p7/poster/setup.py", line 2, in <module>
        import poster
      File "/private/var/folders/2n/90xsl63x57bg30n9x03gjnqw0000gn/T/pip-build-cvncr6p7/poster/poster/__init__.py", line 29, in <module>
        import poster.streaminghttp
      File "/private/var/folders/2n/90xsl63x57bg30n9x03gjnqw0000gn/T/pip-build-cvncr6p7/poster/poster/streaminghttp.py", line 61
        print "send:", repr(value)
                    ^
    SyntaxError: invalid syntax

**Comment by tsamaya** [comment]
Tested with version 2.7, now stated in Doc. 

PR welcome to upgrade this wrapper 😉 

In the meantime, Denis Carriere's geocoder is compatible with python 3 and with our API : https://github.com/DenisCarriere/geocoder

**Comment by tsamaya** [comment]
thanks to @joedborg now the lib support python 3.4 to 3.6
